import { Archivo } from "next/font/google";
import "./globals.css";
import Navigation from "./components/layout/Navigation";


const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
